name: futaba_client
description: A Futaba Client with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  euc: 1.0.2+4
  flutter_state_notifier: 0.4.2
  freezed_annotation: 0.7.1
  html: 0.14.0+3
  http: 0.12.1
  intl: 0.16.1
  provider: 4.1.1
  shared_preferences: 0.5.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.9.0
  freezed: 0.10.8
  pedantic_mono: 1.9.0
  test:

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
      - asset: fonts/NotoSansJP/NotoSansJP-Regular.otf
  assets:
    - fonts/NotoSansJP/OFL.txt
