name: futaba_client
description: A Futaba Client with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  euc: 1.0.2+4
  html: 0.14.0+3
  http: 0.12.0+4
  provider: 4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: 1.8.0

flutter:
  uses-material-design: true
