name: Build apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.2.0
      with:
        flutter-version: '1.12.13+hotfix.8'
        channel: 'stable'
    - name: Run Flutter test
      run: flutter test
    - name: Build debug apk
      run: flutter build apk --debug
    - name: Distribute apk
      run: |
        curl \
         -H "Authorization: token ${{secrets.DEPLOYGATE_TOKEN}}" \
         -F "file=@build/app/outputs/apk/debug/app-debug.apk" \
         -F "message=git:`git rev-parse --short $GITHUB_SHA`" \
         -F "distribution_name=$GITHUB_REF" \
         "https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/apps"
