name: Build apk

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.2.0
      with:
        flutter-version: '1.12.13+hotfix.8'
        channel: 'stable'
    - name: test
      run: flutter test
    - name: build
      run: flutter build apk
