name: Distribute apk

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.2.0
      with:
        flutter-version: '1.17.0'
        channel: 'stable'
    - name: Run Flutter test
      run: flutter test
    - name: Build Release apk
      run: |
        echo storePassword=${{ secrets.STORE_PASSWORD }} >> android/key.properties
        echo keyPassword=${{ secrets.KEY_PASSWORD }} >> android/key.properties
        echo keyAlias=${{ secrets.KEY_ALIAS }} >> android/key.properties
        echo storeFile=../key.jks >> android/key.properties
        echo "${{ secrets.KEY_JKS }}" | openssl base64 -d > android/key.jks
        flutter build apk --release
    - name: Distribute apk
      run: |
        curl \
         -H "Authorization: token ${{secrets.DEPLOYGATE_TOKEN}}" \
         -F "file=@build/app/outputs/apk/release/app-release.apk" \
         -F "message=`git rev-parse --short $GITHUB_SHA`" \
         -F "distribution_name=master" \
         "https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/apps"
